name: reverie
channels:
  - conda-forge
  - ocdb
dependencies:
  - python
  - numpy
  - dask
  - netCDF4
  - h5py
  - gdal
  - pyproj
  - pandas
  - geopandas
  - tqdm
  - timezonefinder
  - pendulum
  - charset-normalizer
  - shapely
  - statsmodels
  - xarray
  - zarr
  - affine
  - rasterio
  - pip
  - scipy
  - pip:
    - p_tqdm